# Generated by Django 4.1.11 on 2023-10-04 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reserve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('zip_code', models.IntegerField()),
                ('service', models.CharField(max_length=30)),
                ('date', models.DateField()),
                ('number_hour', models.IntegerField()),
                ('start_time', models.CharField(max_length=20)),
                ('pets', models.CharField(max_length=10)),
                ('pet_number', models.IntegerField()),
            ],
        ),
    ]
